Vagrant.configure("2") do |config|
    # CONFIGAÇÕES GLOBAIS
    config.vm.box = "ubuntu/focal64" # DEFINIÇÃO DE BOX GLOBAL

    config.vbguest.auto_update = false
    
    # PROVISIONAMENTO GLOBAL
    config.vm.provision "shell", inline: <<-SHELL
        apt update -y
        sudo apt install -y vim git curl
    SHELL

    # DEFINIÇÃO DE CADA VM
    config.vm.define "web01" do |web01|
        # POSSO: SOBRESCREVER A BOX, DAR UM HOSTNAME, DAR UM IP PRIVADO/ESTATICO
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.33.10"
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

        # PROVISIONAMENTO PRÓPRIO DA VM
        web01.vm.provision "shell", inline: <<-SHELL
            sudo apt install -y apache2
        SHELL
    end

    config.vm.define "db01" do |db01|
        # POSSO: SOBRESCREVER A BOX, DAR UM HOSTNAME, DAR UM IP PRIVADO/ESTATICO
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.33.20"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1600"
        end

        # PROVISIONAMENTO PRÓPRIO DA VM
        db01.vm.provision "shell", inline: <<-SHELL
            sudo apt install -y mariadb-server
        SHELL
    end
end