Vagrant.configure("2") do |config|
  # DEFINIR A BOX DO MEU AMBIENTE
  config.vm.box = "ubuntu/focal64"

  # CONFIGURANDO A REDE PRIVADA DA VM
  config.vm.network "private_network", ip: "192.168.56.32"

  # CONFIGURANDO A REDE PÚBLICA DA VM
  config.vm.network "public_network"

  # HABILITAR UMA PASTA SINCRONIZADA ENTRE O HOST E A MAQUINA VIRTUAL
  config.vm.synced_folder "./data", "/vagrant_data"

  # CONFIGURAÇÕES DE PROVEDORES
  config.vm.provider "virtualbox" do |vb|
    # CONFIGURAÇÕES DE QUANTIDADE DE MEMÓRIA DA MÁQUINA VIRTUAL
    vb.memory = "1600"
  end

  # CONFIGURAÇÕES O PROVISIONAMENTO COM UM SCRIPT SHELL (ANSIBLE, DOCKER)
  config.vm.provision "shell", inline: <<-SHELL
    # COMANDOS QUE SERÃO DENTRO DA MÁQUINA
    sudo apt update
    sudo apt install apache2 \
                    ghostscript \
                    libapache2-mod-php \
                    mysql-server \
                    php \
                    php-bcmath \
                    php-curl \
                    php-imagick \
                    php-intl \
                    php-json \
                    php-mbstring \
                    php-mysql \
                    php-xml \
                    php-zip -y

    sudo mkdir -p /srv/www
    sudo chown -R www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

    cat > /etc/apache2/sites-available/wordpress.conf << EOF
<VirtualHost *:80>
    DocumentRoot /srv/www/wordpress
    <Directory /srv/www/wordpress>
        Options FollowSymLinks
        AllowOverride Limit Options FileInfo
        DirectoryIndex index.php
        Require all granted
    </Directory>
    <Directory /srv/www/wordpress/wp-content>
        Options FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>
EOF
    sudo a2ensite wordpress
    sudo a2enmod rewrite
    sudo a2dissite 000-default

    sudo mysql -u root -e 'CREATE DATABASE wordpress;'
    sudo mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "12345678";'
    sudo mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'   
    sudo mysql -u root -e 'FLUSH PRIVILEGES;'

    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/password_here/12345678/' /srv/www/wordpress/wp-config.php

    systemctl restart mysql
    systemctl restart apache2
  SHELL
end